<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="anonymous" ignored="0" name="AddUserWrongTest" tests="1" failures="1" timestamp="2020-06-30T06:54:44 PDT" time="8.415" errors="0">
  <testcase name="testMantisBTAddUserWrong" time="5.762" classname="tests.AddUserWrongTest">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;That username is already being used. Please go back and select another one.&amp;gt; but was:&amp;lt;Invalid e-mail address.&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<That username is already being used. Please go back and select another one.> but was:<Invalid e-mail address.>
at tests.AddUserWrongTest.testMantisBTAddUserWrong(AddUserWrongTest.java:48)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.olianda.treeparallelizer.execution.testcases.TestCaseExecutor.run(TestCaseExecutor.java:56)
at org.olianda.treeparallelizer.execution.NodeExecutor.run(NodeExecutor.java:28)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testMantisBTAddUserWrong -->
</testsuite> <!-- AddUserWrongTest -->
